# Web Elements
data_mapper_svg_icon = "//div[@class='point-mapper-toggles']//div[@class='panel-toggle data-mapper-panel__open']//div[@class='svg-icon w-embed']//*[local-name()='svg']"
data_mapper_header_xpath = "//div[@class='point-data__header_title']//div[contains(text(),'Data Mapper')]"
demographic_menu = "//div[@class='data-category__h1_title']//div[@class='truncate'][contains(text(),'Demographics')]"
age = "//div[@class='data-category__h2_trigger']//div[@class='truncate'][contains(text(),'Age')]"
gender = "//div[@class='data-category__h2_trigger']//div[@class='truncate'][contains(text(),'Gender')]"
race = "//div[@class='data-category__h2_trigger']//div[@class='truncate'][contains(text(),'Race')]"
rob = "//div[@class='data-category__h2_trigger']//div[@class='truncate'][contains(text(),'Region of Birth')]"
citizen = "//div[@class='data-category__h2_trigger']//div[@class='truncate'][contains(text(),'Citizenship')]"
language = "//div[@class='data-category__h2_trigger']//div[@class='truncate'][contains(text(),'Language')]"
youth_population = "//div[@class='truncate'][contains(text(),'Youth population')]"
youths = "//div[contains(text(),'Youths')]"
non_youths = "//div[contains(text(),'Non youth')]"
